spring:
  application:
    name: Sellvia
    profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:local_sellvia_db}
    username: ${DB_USERNAME:adm_local}
    password: ${DB_PASSWORD:adm_local}

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:local_sellvia_db}
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:Senha123}
    locations: classpath:db/migration
    baseline-on-migrate: true

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        discriminator:
          ignore_explicit_for_joined: true

jwt:
  secret: ${JWT_SECRET:secret-temporaria}
  token-expiration: ${JWT_TOKEN_EXPIRATION:18000000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

cloudflare-r2:
  account-id: ${CLOUDFLARE_R2_ACCOUNT_ID:7625cb7491ee3485c49e35fb40762ba2}
  secret-key: ${CLOUDFLARE_R2_ACCESS_KEY:2a9008ccdc9c783c9fd43b1c0394e6aa81f28b72cf42ea0f71ac8c18a77137b2}
  access-key: ${CLOUDFLARE_R2_SECRET_KEY:23596941a23d2dbee8e768471305bd86}
  bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME:sellvia}

logging:
  level:
    software.amazon.awssdk: DEBUG