spring:
  application:
    name: Sellvia
  datasource:
    url: jdbc:h2:mem:sellviadb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

jwt:
  secret: ${JWT_SECRET:secret-temporaria}
  token-expiration: ${JWT_TOKEN_EXPIRATION:18000000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

cloudflare-r2:
  account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
  secret-key: ${CLOUDFLARE_R2_ACCESS_KEY}
  access-key: ${CLOUDFLARE_R2_SECRET_KEY}
  bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}

logging:
  level:
    software.amazon.awssdk: DEBUG