spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas:
      - ${MAIN_APP_SCHEMA}

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        discriminator:
          ignore_explicit_for_joined: true

jwt:
  secret: ${JWT_SECRET}
  token-expiration: ${JWT_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cloudflare-r2:
  account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
  secret-key: ${CLOUDFLARE_R2_ACCESS_KEY}
  access-key: ${CLOUDFLARE_R2_SECRET_KEY}
  bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}

image-service:
  base-url: ${IMAGE_SERVICE_BASE_URL}

logging:
  level:
    software.amazon.awssdk: DEBUG