spring:
  application:
    name: test-application
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  flyway:
    enabled: false

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

jwt:
  secret: secret-de-teste-muito-longa-para-atender-os-requisitos-do-algoritmo
  token-expiration: 3600000
  refresh-token-expiration: 86400000

cloudflare-r2:
  account-id: test-account
  secret-key: test-secret
  access-key: test-access
  bucket-name: test-bucket

logging:
  level:
    root: WARN
    software.amazon.awssdk: ERROR